export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  lightGray: '#B3B4B6',
  accent: '#ec953e',
  accentGray: '#2C2C2C',
  accentPink: '#F96165',
  gold: '#D4AC0D',
  gray: '#BDC3C7',
  light: '#F8F6F6'
};

export const Categories = [
  {
    name: 'Burger',
    image: require('../database/images/burger.png'),
    item: [
      {
        id: '1',
        category: 'product',
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 29.9,
        isTopOfTheWeek: true,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '2',
        category: 'product',
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '3',
        category: 'product',
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 19.9,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        id: '4',
        category: 'product',
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 29.9,
        isTopOfTheWeek: true,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '5',
        category: 'product',
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '6',
        category: 'product',
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 19.9,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
    ],
  },
  {
    name: 'Burger',
    image: require('../database/images/burger.png'),
    item: [
      {
        id: '7',
        category: 'product',
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '8',
        category: 'product',
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '9',
        category: 'product',
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('../database/images/pizza.png'),
    item: [
      {
        id: '10',
        name: 'Pepperoni Pizza',
        category: 'product',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '11',
        category: 'product',
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        id: '12',
        category: 'product',
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.2',
        price: 499,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 45,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/Sliced-Onion.png'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('../database/images/pizza.png'),
    item: [
      {
        id: '13',
        name: 'Pepperoni Pizza',
        category: 'product',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id: '14',
        category: 'product',
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        name: 'Pizza',
        image: require('../database/images/pizza.png'),
        item: [
          {
            id: '15',
            name: 'Pepperoni Pizza',
            category: 'product',
            weight: 250,
            rating: '5.0',
            price: 199,
            isTopOfTheWeek: true,
            image: require('../database/images/pizza/pepperonipizza.png'),
            size: 'Large 14"',
            crust: 'Thin Crust',
            delivery: 30,
            ingredients: [
              require('../database/images/Tomato.png'),
              require('../database/images/cheese.png'),
              require('../database/images/Sliced-Onion.png'),
              require('../database/images/flour.png'),
            ],
          },
          {
            id: '16',
            category: 'product',
            name: 'Plain Cheese Pizza',
            weight: 300,
            rating: '4.5',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../database/images/pizza/plaincheesepizza.png'),
            size: 'Large 16"',
            crust: 'Thin Cheese',
            delivery: 25,
            ingredients: [
              require('../database/images/Sliced-Onion.png'),
              require('../database/images/flour.png'),
              require('../database/images/cheese.png'),
              require('../database/images/Tomato.png'),
            ],
          },
          {
            id: '17',
            category: 'product',
            name: 'Mexican Green Wave',
            weight: 350,
            rating: '4.2',
            price: 499,
            isTopOfTheWeek: false,
            image: require('../database/images/pizza/mexicangreenwave.png'),
            size: 'Large 15"',
            crust: 'Thin Crust',
            delivery: 45,
            ingredients: [
              require('../database/images/flour.png'),
              require('../database/images/cheese.png'),
              require('../database/images/Tomato.png'),
              require('../database/images/Sliced-Onion.png'),
            ],
          },
        ],
      },
      {
        id: '18',
        category: 'product',
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.2',
        price: 499,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 45,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/Sliced-Onion.png'),
        ],
      },
    ],
  },
  {
    name: 'Soft Drinks',
    image: require('../database/images/softdrinks.png'),
    item: [
      {
        id: '19',
        category: 'product',
        name: 'Coco Cola',
        weight: 200,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('../database/images/softdrinks/cocacola.png')],
      },
      {
        id: '20',
        category: 'product',
        name: 'Orange Juice',
        weight: 500,
        rating: '4.5',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/orange.png'),
        size: 'LArge Glass',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('../database/images/softdrinks/orange.png')],
      },
      {
        id: '21',
        category: 'product',
        name: 'Mango Juice',
        weight: 150,
        rating: '4.2',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Small Ice',
        delivery: 5,
        ingredients: [require('../database/images/softdrinks/mango.png')],
      },
    ],
  },
  {
    name: 'Soft Drinks',
    image: require('../database/images/softdrinks.png'),
    item: [
      {
        id: '22',
        category: 'product',
        name: 'Coco Cola',
        weight: 200,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('../database/images/softdrinks/cocacola.png')],
      },
      {
        id: '23',
        category: 'product',
        name: 'Orange Juice',
        weight: 500,
        rating: '4.5',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/orange.png'),
        size: 'LArge Glass',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('../database/images/softdrinks/orange.png')],
      },
      {
        id: '24',
        category: 'product',
        name: 'Mango Juice',
        weight: 150,
        rating: '4.2',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Small Ice',
        delivery: 5,
        ingredients: [require('../database/images/softdrinks/mango.png')],
      },
    ],
  },
];

export const Items = [
  {
    id: '1',
    category: 'product',
    name: 'Biggie Cheese',
    rating: '4.2',
    price: 29.9,
    image: require('../database/images/burger/biggiecheese.png'),
  },
  {
    id: '2',
    category: 'product',
    name: 'Aloo Tikki Burger',
    rating: '4.5',
    price: 99,
    image: require('../database/images/burger/alootikkiburger.png'),
  },
  {
    id: '3',
    category: 'product',
    name: 'Classic Burger',
    rating: '5.0',
    price: 19.9,
    image: require('../database/images/burger/classicburger.png'),
  },
  {
    id: '4',
    category: 'product',
    name: 'Biggie Cheese',
    rating: '4.2',
    price: 29.9,
    image: require('../database/images/burger/biggiecheese.png'),
  },
  {
    id: '5',
    category: 'product',
    name: 'Aloo Tikki Burger',
    rating: '4.5',
    price: 99,
    isTopOfTheWeek: false,
    image: require('../database/images/burger/alootikkiburger.png'),
  },
  {
    id: '6',
    category: 'product',
    name: 'Classic Burger',
    rating: '5.0',
    price: 19.9,
    image: require('../database/images/burger/classicburger.png'),
  },
  {
    id: '7',
    category: 'product',
    name: 'Biggie Cheese',
    rating: '4.2',
    price: 299,
    image: require('../database/images/burger/biggiecheese.png'),
  },
  {
    id: '8',
    category: 'product',
    name: 'Aloo Tikki Burger',
    rating: '4.5',
    price: 99,
    image: require('../database/images/burger/alootikkiburger.png'),
  },
  {
    id: '9',
    category: 'product',
    name: 'Classic Burger',
    rating: '5.0',
    price: 199,
    image: require('../database/images/burger/classicburger.png'),
  },
  {
    id: '10',
    name: 'Pepperoni Pizza',
    category: 'product',
    rating: '5.0',
    price: 199,
    image: require('../database/images/pizza/pepperonipizza.png'),
  },
  {
    id: '11',
    category: 'product',
    name: 'Plain Cheese Pizza',
    rating: '4.5',
    price: 299,
    image: require('../database/images/pizza/plaincheesepizza.png'),
  },
  {
    id: '12',
    category: 'product',
    name: 'Mexican Green Wave',
    rating: '4.2',
    price: 499,
    image: require('../database/images/pizza/mexicangreenwave.png'),
  },
  {
    id: '13',
    name: 'Pepperoni Pizza',
    category: 'product',
    rating: '5.0',
    price: 199,
    image: require('../database/images/pizza/pepperonipizza.png'),
  },
  {
    id: '14',
    category: 'product',
    name: 'Plain Cheese Pizza',
    rating: '4.5',
    price: 299,
    image: require('../database/images/pizza/plaincheesepizza.png'),
  },
  {
    id: '15',
    name: 'Pepperoni Pizza',
    category: 'product',
    rating: '5.0',
    price: 199,
    image: require('../database/images/pizza/pepperonipizza.png'),
  },
  {
    id: '16',
    category: 'product',
    name: 'Plain Cheese Pizza',
    rating: '4.5',
    price: 299,
    image: require('../database/images/pizza/plaincheesepizza.png'),
  },
  {
    id: '17',
    category: 'product',
    name: 'Mexican Green Wave',
    rating: '4.2',
    price: 499,
    image: require('../database/images/pizza/mexicangreenwave.png'),
  },
  {
    id: '18',
    category: 'product',
    name: 'Mexican Green Wave',
    rating: '4.2',
    price: 499,
    image: require('../database/images/pizza/mexicangreenwave.png'),
  },
  {
    id: '19',
    category: 'product',
    name: 'Coco Cola',
    rating: '5.0',
    price: 299,
    image: require('../database/images/softdrinks/cocacola.png'),
  },
  {
    id: '20',
    category: 'product',
    name: 'Orange Juice',
    rating: '4.5',
    price: 199,
    image: require('../database/images/softdrinks/orange.png'),
  },
  {
    id: '21',
    category: 'product',
    name: 'Mango Juice',
    rating: '4.2',
    price: 99,
    image: require('../database/images/softdrinks/mango.png'),
  },
  {
    id: '22',
    category: 'product',
    name: 'Coco Cola',
    rating: '5.0',
    price: 299,
    image: require('../database/images/softdrinks/cocacola.png'),
  },
  {
    id: '23',
    category: 'product',
    name: 'Orange Juice',
    rating: '4.5',
    price: 199,
    image: require('../database/images/softdrinks/orange.png'),
  },
  {
    id: '24',
    category: 'product',
    name: 'Mango Juice',
    rating: '4.2',
    price: 99,
    image: require('../database/images/softdrinks/mango.png'),

  },
]